server:
  port: 8091
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/userservice/**
        - id: LoanService
          uri: http://localhost:8084
          predicates:
            - Path=/loan/**, /employee/**
        - id: authenticationService
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**, /users/**

      discovery:
        locator:
          enable: true
  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka